name: "test"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - 'releases/v*'
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        yarn install
        yarn run all

